apiVersion: v2
name: auth-services
description: IdentityServer, API Gateway, Inventories API and client, plus the IdentityServer SQL Server database and Consul
type: application
version: 0.2.0
appVersion: "1.0.0"
