{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "auth-services.labels" (dict "root" $ "name" .Values.identityDb.name) | nindent 4 }}
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: {{ required "secret.saPassword is required when secret.create is true" .Values.secret.saPassword | quote }}
{{- end }}
